//configuration keys
#define KEY_CONTACT_NAME 0
#define KEY_CONTACT_PHONE 1
#define KEY_MY_NAME 2
#define KEY_HOUR_FORMAT 3
#define KEY_SHOW_BATTERY 4
#define KEY_ICE_BACKGROUND 5
#define KEY_ICE_TEXTCOLOR 6
#define KEY_ME_BACKGROUND 7
#define KEY_ME_TEXTCOLOR 8
#define KEY_SHOW_BT 9

#define BT_STATUS 42

#define BUZZER_INTERVAL 1500
#define MAX_WIDTH 144
