BitmapLayer* connectionSetup();
TextLayer* ICELabelSetup();
TextLayer* ICENameSetup();
TextLayer* ICEPhoneSetup();
TextLayer* meSetup();
TextLayer* timeSetup();
TextLayer* dateSetup();
TextLayer* batterySetup();
void processLayers();
void loadLayers();
void setDisplayData();
void setBackgroundColor(int ,TextLayer * );
void setTextColor(int ,TextLayer * );
